### ISSUE TITLE
Add ability to create a parameter at the pipeline level

### ISSUE THREAD

**Issue by David-M-IBM** [cloud-native-toolkit/cdk8s-pipelines#42]
Currently you cannot create a parameter that is only defined in the pipeline and not in a task. There is a common use case where a task has a script as an input where a pipeline parameter is used within the script but isn't defined as a param for the task. Example pictured below:
<img width="1360" alt="image" src="https://github.com/cloud-native-toolkit/cdk8s-pipelines/assets/83517881/0235c323-b111-4341-8a65-3aa5cd9918ee">

Adding a .withStringParam to the PipelineBuilder class would resolve this issue. It would also be nice if there was a way within the task to reference the pipeline param so that it could be checked during synth.

**What the function would look like in main.ts:**
   new PipelineBuilder(this, 'test-pipeline')
       .withStringParam(new ParameterBuilder('SCRIPT').withDefault("test")
       
       
**What the piece generated pipeline yaml would look like:**
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  params:
    - name: SCRIPT
       type: string
       default: "test"

**Comment by snehajais22** [comment]
Closed by https://github.com/cloud-native-toolkit/cdk8s-pipelines/pull/46
